### ISSUE TITLE
Error when running The setup for BlizzTV.exe

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bonesoul/blizztv#124]
```
What steps will reproduce the problem?
1. Run .exe, then click next, error follows
2. Can not launch modules
3. Have .net 4.0 installed

What is the expected output? What do you see instead?
-Can not run app or see modules

What version of the product are you using? On what operating system?
-Windows Vista

Please provide any additional information below.

Error message when running .exe

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for 
'BlizzTV.ModuleLib.ModuleManager' threw an exception. ---> 
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of 
the requested types. Retrieve the LoaderExceptions property for more 
information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at BlizzTV.ModuleLib.ModuleManager.ScanModules()
   at BlizzTV.ModuleLib.ModuleManager..ctor()
   at BlizzTV.ModuleLib.ModuleManager..cctor()
   --- End of inner exception stack trace ---
   at BlizzTV.ModuleLib.ModuleManager.get_Instance()
   at BlizzTV.UI.frmMain.LoadModules()
   at BlizzTV.UI.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlizzTV
    Assembly Version: 0.18.4016.27292
    Win32 Version: 0.18.4016.27292
    CodeBase: file:///C:/Users/JayD/Desktop/BlizzTV/BlizzTV.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Nini
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/JayD/Desktop/BlizzTV/Nini.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AxInterop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/JayD/Desktop/BlizzTV/AxInterop.ShockwaveFlashObjects.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

Original issue reported on code.google.com by `JeremyDe...@gmail.com` on 30 Dec 2010 at 3:51

**Comment by GoogleCodeExporter** [comment]
```
Its at the select plugins I get the error pasted, it happens in Windows XP and 
Vista
```

Original comment by `JeremyDe...@gmail.com` on 30 Dec 2010 at 4:01

**Comment by GoogleCodeExporter** [comment]
```
Issue was caused by missing Microsoft Visual C++ 2010 Redistributable Package 
(x86) runtimes 
(http://www.microsoft.com/downloads/en/details.aspx?familyid=A7B7A05E-6DE6-4D3A-
A423-37BF0912DB84&displaylang=en) which is actually required by the irrKlang 
engine. Will be fixed with a hotfix to dependency-checker.
```

Original comment by `shalafir...@gmail.com` on 30 Dec 2010 at 7:15
- Changed state: **BugReport**
- Added labels: **Priority-High**, **Usability**, **Milestone-0.19-Beta**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `shalafir...@gmail.com` on 30 Dec 2010 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
Yes, I have the same problem but after installing the Microsoft Visual C++ 2010 
Redistributable Package (x86) runtimes, it was fixed.
```

Original comment by `eds...@gmail.com` on 31 Dec 2010 at 6:31

**Comment by GoogleCodeExporter** [comment]
```
Fixed with r289, will be releasing the hotfix soon.
```

Original comment by `shalafir...@gmail.com` on 31 Dec 2010 at 9:57

**Comment by GoogleCodeExporter** [comment]
```
Tested & confirmed the fix with my vulnerable XP machine.
```

Original comment by `shalafir...@gmail.com` on 31 Dec 2010 at 10:16
- Changed state: **Fixed**
