### ISSUE TITLE
Registry permissions bug

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bonesoul/blizztv#128]
```
Got reports from users having problems with registry access;

[01:00:20]  <AgentSmith> i got an issue with 0.18b
[01:00:44]  <AgentSmith> http://pastebin.com/Q1twRTNf
[01:00:48]  <AgentSmith> when i try to open preference
[01:00:53]  <AgentSmith> this does not happen with 0.17b

************** Exception Text **************
System.Security.SecurityException: Requested registry access is not allowed.
   at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at BlizzTV.CommonLib.Helpers.Registry.GetKey(RootKey rootKey, String key)
   at BlizzTV.CommonLib.Helpers.SystemStartup.get_Enabled()
   at BlizzTV.UI.frmPreferences.LoadSettings()
   at BlizzTV.UI.frmPreferences.frmPreferences_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
The Zone of the assembly that failed was:
MyComputer
```

Original issue reported on code.google.com by `shalafir...@gmail.com` on 3 Jan 2011 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
Running the program with administrator permissions works as a quick-fix.
```

Original comment by `shalafir...@gmail.com` on 3 Jan 2011 at 10:58

**Comment by GoogleCodeExporter** [comment]
```
Should be fixed as of r296.
```

Original comment by `shalafir...@gmail.com` on 3 Jan 2011 at 12:38
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 132 has been merged into this issue.
```

Original comment by `shalafir...@gmail.com` on 5 Jan 2011 at 8:41
