### ISSUE TITLE
Video module: HoNReplays key not found error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bonesoul/blizztv#185]
```
Reported over: 
http://forums.heroesofnewerth.com/showpost.php?p=13163911&postcount=9

When trying to open a video from HonReplays channel, application crashes;

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present 
in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BlizzTV.Videos.Video.Process()
   at BlizzTV.Videos.PlayerForm..ctor(Video video)
   at BlizzTV.Videos.Video.Play()
   at BlizzTV.Videos.Video.Open(Object sender, EventArgs e)
   at BlizzTV.UI.TreeItem.Open(Object sender, EventArgs e)
   at BlizzTV.UI.MainForm.TreeView_NodeMouseDoubleClick(Object sender, TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.OnNodeMouseDoubleClick(TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlizzTV
    Assembly Version: 0.21.4079.40232
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Nini
    Assembly Version: 1.1.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
irrKlang.NET4
    Assembly Version: 1.0.3861.18767
    Win32 Version: 
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/irrKlang.NET4.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AxInterop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
AxInterop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.4.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
uk550mmv
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Esent.Interop
    Assembly Version: 1.5.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
Esent.Collections
    Assembly Version: 1.0.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
yhiulzur
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Interop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 0.21.4079.40232
    CodeBase: file:///E:/coding/blizztv/trunk/blizztv/bin/Release/BlizzTV.exe
----------------------------------------
tj0jlrqb
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

Workaround: Using external web-browser as the video player.
```

Original issue reported on code.google.com by `shalafir...@gmail.com` on 4 Mar 2011 at 4:20

**Comment by GoogleCodeExporter** [comment]
```
Issue is caused by the updated subscriptions catalog using different casing for 
provider names. 
```

Original comment by `shalafir...@gmail.com` on 4 Mar 2011 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
Within next version we should ignore the casing for subscription catalog links.
```

Original comment by `shalafir...@gmail.com` on 4 Mar 2011 at 4:26

**Comment by GoogleCodeExporter** [comment]
```
Fixed as of r480.
```

Original comment by `shalafir...@gmail.com` on 17 Mar 2011 at 6:15
- Changed state: **Fixed**
