### ISSUE TITLE
On windows-vista application is not able to access blizztv.ini and so files -- which requires administrative permissions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bonesoul/blizztv#195]
```
On windows-vista application is not able to access blizztv.ini and so files -- 
which requires administrative permissions.

So handle the exception and tell the user to run in administrative mode if 
required.
```

Original issue reported on code.google.com by `shalafir...@gmail.com` on 21 Mar 2011 at 6:55

**Comment by GoogleCodeExporter** [comment]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program Files 
(x86)\BlizzTV\blizztv.ini' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at Nini.Ini.IniDocument.Save(String filePath)
   at Nini.Config.IniConfigSource.Save()
   at BlizzTV.Settings.SettingsManager.Save()
   at BlizzTV.UI.Wizard.frmWizardPlugins.Finish()
   at BlizzTV.UI.Wizard.frmWizardHost.Step(Boolean forward)
   at BlizzTV.UI.Wizard.frmWizardHost.ButtonNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlizzTV
    Assembly Version: 0.22.4097.35025
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files%20(x86)/BlizzTV/BlizzTV.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Nini
    Assembly Version: 1.1.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files%20(x86)/BlizzTV/BlizzTV.exe
----------------------------------------
irrKlang.NET4
    Assembly Version: 1.0.3861.18767
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/BlizzTV/irrKlang.NET4.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AxInterop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files%20(x86)/BlizzTV/BlizzTV.exe
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files%20(x86)/BlizzTV/BlizzTV.exe
----------------------------------------
AxInterop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files%20(x86)/BlizzTV/BlizzTV.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

Original comment by `shalafir...@gmail.com` on 21 Mar 2011 at 7:02

**Comment by GoogleCodeExporter** [comment]
```
Issue also valid for Windows 7.


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program 
Files\BlizzTV\blizztv.ini' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at Nini.Ini.IniDocument.Save(String filePath)
   at Nini.Config.IniConfigSource.Save()
   at BlizzTV.Settings.SettingsManager.Save()
   at BlizzTV.UI.Wizard.frmWizardPlugins.Finish()
   at BlizzTV.UI.Wizard.frmWizardHost.Step(Boolean forward)
   at BlizzTV.UI.Wizard.frmWizardHost.ButtonNext_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlizzTV
    Assembly Version: 0.22.4097.35025
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files/BlizzTV/BlizzTV.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Nini
    Assembly Version: 1.1.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files/BlizzTV/BlizzTV.exe
----------------------------------------
irrKlang.NET4
    Assembly Version: 1.0.3861.18767
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/BlizzTV/irrKlang.NET4.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AxInterop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files/BlizzTV/BlizzTV.exe
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files/BlizzTV/BlizzTV.exe
----------------------------------------
AxInterop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 0.22.4097.35025
    CodeBase: file:///C:/Program%20Files/BlizzTV/BlizzTV.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

Original comment by `shalafir...@gmail.com` on 21 Mar 2011 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
Application now uses local-app data folder for storage. (r497).
```

Original comment by `shalafir...@gmail.com` on 22 Mar 2011 at 8:40
- Changed state: **Fixed**
