### ISSUE TITLE
Events stuck on "Updating Events..."

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bonesoul/blizztv#199]
```
Does your computer meet these dependencies?
* .net 4.0 framework installed?
* latest adoble flash player installed?

Your operating system: Win 7 64 bit, Home Premium

BlizzTV version: 0.22.4100.40332

What steps will reproduce the problem?
1.  Open BlizzTV - modules go through their 'updating' routine, but Events just 
stays stuck on "Updating Events."  I can open it to show Today, Upcoming, Past 
but there are no entries in any of those.  
2.  Doing File -> Modules -> Refresh All has Streams, Podcasts, Videos, and 
Feeds all updating properly but Events remains stuck at Updating.
3.  Uninstalling/reinstalling and attempting the Repair option on the installer 
result in no change.

Please provide any additional information below.


```

Original issue reported on code.google.com by `bentonwh...@gmail.com` on 15 Apr 2011 at 9:48

**Comment by GoogleCodeExporter** [comment]
```
Seems caused by teamliquid, i'll be checking the issue.

[01:26:20][Error]: WebReader encountered an exception while reading url http://w
ww.teamliquid.net/calendar/xml/calendar.xml - System.Net.WebException: The remot
e server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at BlizzTV.Utility.Web.WebReader.Read(String url, Int32 timeout)
```

Original comment by `shalafir...@gmail.com` on 15 Apr 2011 at 10:27
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Low**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r508.
```

Original comment by `shalafir...@gmail.com` on 15 Apr 2011 at 11:05
- Changed state: **Fixed**
