### ISSUE TITLE
App crashes after doubleclick on upcoming events

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bonesoul/blizztv#52]
```
When I doubleclick on the upcoming node under Events the application crashes.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 
'Microsoft.VisualBasic.PowerPacks.Vs, Version=10.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann 
die angegebene Datei nicht finden.
File name: 'Microsoft.VisualBasic.PowerPacks.Vs, Version=10.0.0.0, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at LibEvents.frmEventViewer.InitializeComponent()
   at LibEvents.frmEventViewer..ctor(Event Event)
   at LibEvents.Event.DoubleClicked(Object sender, EventArgs e)
   at BlizzTV.TreeItem.DoubleClicked(Object sender, TreeNodeMouseClickEventArgs e)
   at BlizzTV.frmMain.TreeView_NodeMouseDoubleClick(Object sender, TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.OnNodeMouseDoubleClick(TreeNodeMouseClickEventArgs e)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value 
[HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure 
logging.
To turn this feature off, remove the registry value 
[HKLM\Software\Microsoft\Fusion!EnableLog].



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
BlizzTV
    Assembly Version: 0.12.3970.27243
    Win32 Version: 0.12.3970.27243
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/BlizzTV.exe
----------------------------------------
LibBlizzTV
    Assembly Version: 0.12.3970.26344
    Win32 Version: 0.12.3970.26344
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/LibBlizzTV.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
LibEvents
    Assembly Version: 0.12.3970.27243
    Win32 Version: 0.12.3970.27243
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/LibEvents.DLL
----------------------------------------
LibFeeds
    Assembly Version: 0.12.3970.27243
    Win32 Version: 0.12.3970.27243
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/LibFeeds.DLL
----------------------------------------
LibStreams
    Assembly Version: 0.12.3970.27243
    Win32 Version: 0.12.3970.27243
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/LibStreams.DLL
----------------------------------------
LibVideoChannels
    Assembly Version: 0.12.3970.27243
    Win32 Version: 0.12.3970.27243
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/LibVideoChannels.DLL
----------------------------------------
AxInterop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/AxInterop.ShockwaveFlashObjects.DLL
----------------------------------------
Interop.ShockwaveFlashObjects
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/Interop.ShockwaveFlashObjects.DLL
----------------------------------------
Esent.Collections
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/Esent.Collections.DLL
----------------------------------------
Esent.Interop
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/Esent.Interop.DLL
----------------------------------------
System.Windows.Forms.Calendar
    Assembly Version: 1.0.3965.23369
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/bizztv/Blizztv-0.12-beta/System.Windows.Forms.Calendar.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

Original issue reported on code.google.com by `andre.sc...@gmail.com` on 15 Nov 2010 at 6:01
- Merged into: #35

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting the issue, it is actually duplicate of Issue35 and i've 
already fixed. It will be available with the next release.
```

Original comment by `shalafir...@gmail.com` on 15 Nov 2010 at 7:57
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Was a Milestone-0.19-Beta issue.
```

Original comment by `shalafir...@gmail.com` on 19 Nov 2010 at 2:07
- Added labels: **Milestone-0.19-Beta**
